PrikupljanjePodataka/Controllers/KluboviController.cs
using PrikupljanjePodataka.DTO;
using PrikupljanjePodataka.Repozitoriji;
using System.Web.Mvc;

namespace PrikupljanjePodataka.Controllers
{
    public class KluboviController : Controller
    {
        // GET: Klubovi
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(KlubDTO klub)
        {
            var klubRepozitorij = new KlubRepozitorij();
            var rezultat = klubRepozitorij.SpremiKlub(klub);
            return View();
        }


        public ActionResult Pripadnost()
        {
            var klubRepozitorij = new KlubRepozitorij();
            var veslacRepozitorij = new VeslacRepozitorij();

            var klubovi = klubRepozitorij.DohvatiKlubove();
            var veslaci = veslacRepozitorij.DohvatiVeslace();

            var model = new PripadnostKlubuViewModel()
            {
                Klubovi = klubovi,
                Veslaci = veslaci
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Pripadnost(PripadnostKlubuDTO pripadnost)
        {

            var klubRepozitorij = new KlubRepozitorij();
            var veslacRepozitorij = new VeslacRepozitorij();

            var rezultat = klubRepozitorij.SpremiPripadnostKlubu(pripadnost);

            var klubovi = klubRepozitorij.DohvatiKlubove();
            var veslaci = veslacRepozitorij.DohvatiVeslace();

            var model = new PripadnostKlubuViewModel()
            {
                Klubovi = klubovi,
                Veslaci = veslaci
            };


            return View(model);
        }

    }
}

PrikupljanjePodataka/Controllers/PosadeController.cs
using PrikupljanjePodataka.DTO;
using PrikupljanjePodataka.PoslovniSloj;
using PrikupljanjePodataka.Repozitoriji;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrikupljanjePodataka.Controllers
{
    public class PosadeController : Controller
    {
        // GET: Posade
        public ActionResult Index()
        {
            var regataRepozitorij = new RegataRepozitorij();
            var regate = regataRepozitorij.DohvatiRegate();
            return View(regate);
        }

        public ActionResult Regata(int id)
        {
            var kategorijeRepozitorij = new KategorijaRepozitorij();
            var regataRepozitorij = new RegataRepozitorij();
            var veslacRepozitorij = new VeslacRepozitorij();

            var kategorije = kategorijeRepozitorij.DohvatiKategorijePremaRegati(id);
            var regata = regataRepozitorij.DohvatiRegatu(id);
            var veslaci = veslacRepozitorij.DohvatiVeslace();
            var model = new PosadaViewModel()
            {
                Regata = regata,
                Kategorije = kategorije,
                Veslaci = veslaci
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Regata(int id, PosadaDTO posada)
        {
            posada.ListaIdVeslac = new List<int>();
            for (var i = 0; i < 9; i++)
            {
                var imeParametra = $"Veslac{i}";
                var parametar = Request.Params[imeParametra];
                if (string.IsNullOrWhiteSpace(parametar))
                {
                    break;
                }

                if (Int32.TryParse(parametar, out var intParametar))
                {
                    posada.ListaIdVeslac.Add(intParametar);
                }
                else
                {
                    break;
                }
            }
            var posadaServis = new Posada();
            var rezultat = posadaServis.StvoriPosadu(posada);


            var kategorijeRepozitorij = new KategorijaRepozitorij();
            var regataRepozitorij = new RegataRepozitorij();
            var veslacRepozitorij = new VeslacRepozitorij();

            var kategorije = kategorijeRepozitorij.DohvatiKategorijePremaRegati(id);
            var regata = regataRepozitorij.DohvatiRegatu(id);
            var veslaci = veslacRepozitorij.DohvatiVeslace();
            var model = new PosadaViewModel()
            {
                Regata = regata,
                Kategorije = kategorije,
                Veslaci = veslaci
            };
            return View(model);
        }
    }
}

PrikupljanjePodataka/Controllers/UtrkeController.cs
using PrikupljanjePodataka.DTO;
using PrikupljanjePodataka.PoslovniSloj;
using PrikupljanjePodataka.Repozitoriji;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrikupljanjePodataka.Controllers
{
    public class UtrkeController : Controller
    {
        // GET: Utrke
        public ActionResult Index()
        {
            var regataRepozitorij = new RegataRepozitorij();
            var regate = regataRepozitorij.DohvatiRegate();
            return View(regate);
        }

        public ActionResult Regata(int id)
        {
            var kategorijeRepozitorij = new KategorijaRepozitorij();
            var regataRepozitorij = new RegataRepozitorij();
            var kategorije = kategorijeRepozitorij.DohvatiKategorijePremaRegati(id);
            var regata = regataRepozitorij.DohvatiRegatu(id);
            var model = new UtrkaViewModel()
            {
                Regata = regata,
                Kategorije = kategorije
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Regata(int id, UtrkaDTO utrka)
        {
            var kategorijeRepozitorij = new KategorijaRepozitorij();
            var regataRepozitorij = new RegataRepozitorij();
            var utrkaRepozitorij = new UtrkaRepozitorij();

            var rezultat = utrkaRepozitorij.SpremiUtrku(utrka);
            var kategorije = kategorijeRepozitorij.DohvatiKategorijePremaRegati(id);
            var regata = regataRepozitorij.DohvatiRegatu(id);
            var model = new UtrkaViewModel()
            {
                Regata = regata,
                Kategorije = kategorije
            };
            return View(model);
        }

        public ActionResult Posada()
        {
            //odaberi regatu
            var regataRepozitorij = new RegataRepozitorij();
            var regate = regataRepozitorij.DohvatiRegate();
            return View(regate);
        }

        //idRegata
        public ActionResult PosadaKategorija(int id)
        {
            //odaberi kategoriju
            var kategorijeRepozitorij = new KategorijaRepozitorij();
            var kategorije = kategorijeRepozitorij.DohvatiKategorijePremaRegati(id);
            return View(kategorije);
        }

        //idKategorija
        public ActionResult PosadaUtrka(int id)
        {
            //dodaj posadu u utrku
            var utrkaServisi = new Utrka();
            var utrke = utrkaServisi.DohvatiUtrkeIzKategorije(id);

            var posadaRepozitorij = new PosadaRepozitorij();
            var posade = posadaRepozitorij.DohvatiPosadeIzKategorije(id);
            var model = new PosadaUUtrkuViewModel()
            {
                Posade = posade,
                Utrke = utrke
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult PosadaUtrka(int id, PosadaUUtrciDTO posada)
        {
            //pospremi posadu
            var utrkaRepozitorij = new UtrkaRepozitorij();
            utrkaRepozitorij.DodajPosaduUUtrku(posada);

            var posadaRepozitorij = new PosadaRepozitorij();
            var utrkaServisi = new Utrka();
            var utrke = utrkaServisi.DohvatiUtrkeIzKategorije(id);


            var posade = posadaRepozitorij.DohvatiPosadeIzKategorije(id);
            var model = new PosadaUUtrkuViewModel()
            {
                Posade = posade,
                Utrke = utrke
            };
            return View(model);
        }


    }
}

PrikupljanjePodataka/Controllers/VeslaciController.cs
using PrikupljanjePodataka.DTO;
using PrikupljanjePodataka.Repozitoriji;
using System;
using System.Web.Mvc;

namespace PrikupljanjePodataka.Controllers
{
    public class VeslaciController : Controller
    {
        // GET: Veslaci
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(VeslacDTO veslac)
        {
            var veslacRepozitorij = new VeslacRepozitorij();
            var rezultat = veslacRepozitorij.SpremiVeslaca(veslac);

            return View();
        }

        public ActionResult Masa()
        {
            var veslacRepozitorij = new VeslacRepozitorij();
            var veslaci = veslacRepozitorij.DohvatiVeslace();
            return View(veslaci);
        }

        [HttpPost]
        public ActionResult Masa(MasaDTO masa)
        {
            var tezina = Request.Params["Masa"];
            var idVeslac = Request.Params["IdVeslac"];
            var VrijemeMjerenje = Request.Params["VrijemeMjerenje"];
            masa = new MasaDTO()
            {
                IdVeslac = int.Parse(idVeslac),
                Masa = float.Parse(tezina),
                VrijemeMjerenje = DateTime.Parse(VrijemeMjerenje)
            };

            var veslacRepozitorij = new VeslacRepozitorij();
            veslacRepozitorij.SpremiMasuVeslaca(masa);
            var veslaci = veslacRepozitorij.DohvatiVeslace();
            return View(veslaci);
        }

        public ActionResult Visina()
        {
            var veslacRepozitorij = new VeslacRepozitorij();
            var veslaci = veslacRepozitorij.DohvatiVeslace();
            return View(veslaci);
        }

        [HttpPost]
        public ActionResult Visina(VisinaDTO visina)
        {
            var visinaInput = Request.Params["Masa"];
            var idVeslac = Request.Params["IdVeslac"];
            var VrijemeMjerenje = Request.Params["VrijemeMjerenje"];
            visina = new VisinaDTO()
            {
                IdVeslac = int.Parse(idVeslac),
                Visina = float.Parse(visinaInput),
                VrijemeMjerenje = DateTime.Parse(VrijemeMjerenje)
            };

            var veslacRepozitorij = new VeslacRepozitorij();
            veslacRepozitorij.SpremiVisinuVeslaca(visina);
            var veslaci = veslacRepozitorij.DohvatiVeslace();
            return View(veslaci);
        }
    }
}

PrikupljanjePodataka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="~/Content/jquery-ui.min.css">
    <script src="~/Scripts/jquery-ui.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Veslački informacijski sustav", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Regate", "Index", "Home", new { area = "" }, null)</li>




                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Kategorije
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Stvaranje kategorije", "Index", "Kategorije", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Registracija posade", "Index", "Posade", new { area = "" }, null)</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Utrke
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Stvaranje utrke", "Index", "Utrke", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Dodavanje posade", "Posada", "Utrke", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Spremanje rezultata", "Index", "Rezultati", new { area = "" }, null)</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Veslači
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Stvaranje veslača", "Index", "Veslaci", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Visina", "Visina", "Veslaci", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Težina", "Masa", "Veslaci", new { area = "" }, null)</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Klubovi
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Registracija kluba", "Index", "Klubovi", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Registracija veslača", "Pripadnost", "Klubovi", new { area = "" }, null)</li>

                        </ul>
                    </li>

                    <li>@Html.ActionLink("Treninzi", "Index", "Treninzi", new { area = "" }, null)</li>
                    


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>FER 2018.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>