PrikupljanjePodataka/Controllers/RezultatiController.cs
using PrikupljanjePodataka.DTO;
using PrikupljanjePodataka.PoslovniSloj;
using PrikupljanjePodataka.Repozitoriji;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrikupljanjePodataka.Controllers
{
    public class RezultatiController : Controller
    {
        // GET: Rezultati
        public ActionResult Index()
        {
            var regataRepozitorij = new RegataRepozitorij();
            var regate = regataRepozitorij.DohvatiRegate();
            return View(regate);
        }

        //idRegata
        public ActionResult Regata(int id)
        {
            //odaberi utrku
            var utrkaServisi = new Utrka();
            var utrke = utrkaServisi.DohvatiUtrkeIzRegate(id);
            return View(utrke);
        }

        //idUtrka
        public ActionResult Spremi(int id)
        {
            var repozitorijPosade = new PosadaRepozitorij();
            var posade = repozitorijPosade.DohvatiPosadeIzUtrke(id);
            return View(posade);
        }

        [HttpPost]
        public ActionResult Spremi(int id,RezultatDTO ulaz)
        {
            var minute = Int32.Parse(Request.Params["Minute"]);
            var sekunde = Int32.Parse(Request.Params["Sekunde"]);
            var stotinke = Int32.Parse(Request.Params["Stotinke"]);
            var idRezultat = Int32.Parse(Request.Params["IdRezultat"]);
            var rezultat = new RezultatDTO()
            {
                IdRezultat = idRezultat,
                Vrijeme = new TimeSpan(0, 0, minute, sekunde, stotinke * 10)
            };

            var repozitorijRezultati = new RezultatRepozitorij();
            var uspjeh = repozitorijRezultati.SpremiRezultat(rezultat);

            var repozitorijPosade = new PosadaRepozitorij();
            var posade = repozitorijPosade.DohvatiPosadeIzUtrke(id);
            return View(posade);
        }

    }
}

PrikupljanjePodataka/Views/Rezultati/Index.cshtml
@model IEnumerable<PrikupljanjePodataka.DTO.SelectDTO>

<h2>Odaberite regatu</h2>

<div class="list-group">
    @foreach (var item in Model)
    {
        @Html.ActionLink(item.Value, "Regata", "Rezultati", new { id = item.Id }, new { @class = "list-group-item list-group-item-action" })
    }
</div>

PrikupljanjePodataka/Views/Rezultati/Regata.cshtml
@model IEnumerable<PrikupljanjePodataka.DTO.SelectDTO>

<h2>Odaberite utrku</h2>

<div class="list-group">
    @foreach (var item in Model)
    {
        @Html.ActionLink(item.Value, "Spremi", "Rezultati", new { id = item.Id }, new { @class = "list-group-item list-group-item-action" })
    }
</div>

PrikupljanjePodataka/Views/Rezultati/Spremi.cshtml
@model IEnumerable<PrikupljanjePodataka.DTO.SelectDTO>
@{
    ViewBag.Title = "Vrijeme posade";
}

<h2>Pohranite vrijeme posade</h2>

<form class="form-horizontal" method="post">
    <div class="form-group">
        <label>Posada:</label>
        <select class="form-control" name="IdRezultat">
            @foreach (var posada in Model)
            {
                <option value="@posada.Id" selected>@posada.Value</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label>Rezultat:</label>
        <input type="number" class="form-control" name="Minute" step="1" placeholder="minute" required>
        <input type="number" class="form-control" name="Sekunde" step="1" placeholder="sekunde" required>
        <input type="number" class="form-control" name="Stotinke" step="1" placeholder="stotinke" required>
    </div>
    <button type="submit" class="btn btn-default">Spremi</button>
</form>